import type { PlaceCandidate } from "./types";
import { haversineKm, estimateDriveMinutes } from "./scoring";

/**
 * Sample scan results — a realistic Bucovina dataset used when the live
 * OSM APIs are unreachable (offline dev, sandboxed CI) or when the platform
 * runs in demo mode. Mirrors exactly what a live Overpass scan around
 * Gura Humorului would classify, so the full flow (scan → review →
 * approve → guides/itineraries/AI) is demonstrable end-to-end without
 * network access or API keys.
 */
const RAW: Array<Omit<PlaceCandidate, "distanceKm" | "driveMinutes" | "source">> = [
  { sourceRef: "sample/voronet", name: "Mănăstirea Voroneț", nameEn: "Voroneț Monastery", category: "culture", subcategory: "monastery", description: { ro: "Mănăstire UNESCO, celebră pentru albastrul de Voroneț.", en: "UNESCO monastery, famous for its Voroneț blue." }, tags: ["unesco", "pictură murală"], goodFor: ["culture", "family", "rainy-day"], lat: 47.5172, lng: 25.8642, website: "http://www.voronet.ro", openingHours: "09:00-17:00", qualityScore: 95, image: "/images/explore/voronet.webp" },
  { sourceRef: "sample/humor", name: "Mănăstirea Humor", nameEn: "Humor Monastery", category: "culture", subcategory: "monastery", description: { ro: "Mănăstire pictată UNESCO, la câțiva km de Gura Humorului.", en: "UNESCO painted monastery, a few km from Gura Humorului." }, tags: ["unesco"], goodFor: ["culture", "family"], lat: 47.5983, lng: 25.8567, qualityScore: 85, image: "/images/explore/0b426843dddfece952b3c3aa027bd354.jpg" },
  { sourceRef: "sample/muzeul-obiceiurilor", name: "Muzeul Obiceiurilor Populare din Bucovina", nameEn: "Bucovina Folk Customs Museum", category: "culture", subcategory: "museum", description: { ro: "Muzeu etnografic în centrul orașului Gura Humorului.", en: "Ethnographic museum in the center of Gura Humorului." }, tags: ["muzeu", "tradiții"], goodFor: ["culture", "rainy-day", "family"], lat: 47.5546, lng: 25.8898, qualityScore: 70 },
  { sourceRef: "sample/piatra-pinului", name: "Piatra Pinului", nameEn: "Piatra Pinului Viewpoint", category: "nature", subcategory: "viewpoint", description: { ro: "Belvedere cu panoramă asupra orașului și văii Moldovei.", en: "Viewpoint overlooking the town and the Moldova valley." }, tags: ["belvedere", "fotografie"], goodFor: ["romantic", "adventure"], lat: 47.5442, lng: 25.8735, qualityScore: 55 },
  { sourceRef: "sample/arinis-park", name: "Parcul Ariniș", nameEn: "Ariniș Park", category: "family", subcategory: "park", description: { ro: "Parc de agrement cu alei, locuri de joacă și zonă de picnic.", en: "Leisure park with alleys, playgrounds and picnic areas." }, tags: ["parc", "picnic"], goodFor: ["family", "kids", "relax"], lat: 47.5487, lng: 25.8829, qualityScore: 65 },
  { sourceRef: "sample/tiroliana", name: "Mega Tiroliana Bucovina", nameEn: "Mega Zipline Bucovina", category: "adventure", subcategory: "zip_line", description: { ro: "Una dintre cele mai lungi tiroliene din România.", en: "One of the longest ziplines in Romania." }, tags: ["adrenalină"], goodFor: ["adventure", "kids", "family"], lat: 47.5462, lng: 25.8804, openingHours: "10:00-18:00", qualityScore: 75, image: "/images/explore/aad6d71e5cc8168f3b107ef126924f95.jpg" },
  { sourceRef: "sample/partia-soimul", name: "Pârtia Șoimul", nameEn: "Șoimul Ski Slope", category: "sport", subcategory: "piste", description: { ro: "Pârtie de schi cu telescaun, deschisă iarna.", en: "Ski slope with chairlift, open in winter." }, tags: ["schi", "iarnă"], goodFor: ["adventure", "family"], lat: 47.5449, lng: 25.8763, qualityScore: 60 },
  { sourceRef: "sample/best-western-spa", name: "SPA Bucovina", nameEn: "Bucovina SPA", category: "wellness", subcategory: "spa", description: { ro: "Centru SPA cu piscină interioară, saună și masaj.", en: "SPA center with indoor pool, sauna and massage." }, tags: ["spa", "piscină"], goodFor: ["relax", "romantic", "rainy-day"], lat: 47.5563, lng: 25.8871, phone: "+40 230 207 000", qualityScore: 70 },
  { sourceRef: "sample/trail-codrii", name: "Traseul Codrii Voronețului", nameEn: "Voroneț Forest Trail", category: "trail", subcategory: "hiking", description: { ro: "Traseu ușor de drumeție prin pădure, spre mănăstire.", en: "Easy forest hiking trail towards the monastery." }, tags: ["drumeție", "pădure"], goodFor: ["family", "adventure"], lat: 47.5299, lng: 25.8688, qualityScore: 50 },
  { sourceRef: "sample/rest-bucovina", name: "Restaurant Casa Bucovineană", nameEn: "Casa Bucovineană Restaurant", category: "restaurant", subcategory: "regional", description: { ro: "Bucătărie tradițională bucovineană: păstrăv, tochitură, poale-n brâu.", en: "Traditional Bucovina cuisine: trout, stew, sweet cheese pies." }, tags: ["tradițional"], goodFor: ["family", "romantic", "evening"], lat: 47.5539, lng: 25.8912, phone: "+40 230 111 222", openingHours: "11:00-23:00", qualityScore: 80, image: "/images/restaurant/bistro-local.webp" },
  { sourceRef: "sample/rest-vh", name: "Restaurant Valea Humorului", nameEn: "Valea Humorului Restaurant", category: "restaurant", subcategory: "regional", description: { ro: "Restaurant cu terasă și meniu local, potrivit pentru familii.", en: "Terrace restaurant with a local menu, family friendly." }, tags: ["terasă"], goodFor: ["family", "kids"], lat: 47.5578, lng: 25.8843, openingHours: "10:00-22:00", qualityScore: 65, image: "/images/restaurant/restaurant-terrace.webp" },
  { sourceRef: "sample/pizzeria-centru", name: "Pizzeria Centrală", nameEn: "Central Pizzeria", category: "restaurant", subcategory: "pizza", description: { ro: "Pizzerie în centru, livrare locală.", en: "Pizzeria in the center, local delivery." }, tags: ["pizza"], goodFor: ["family", "kids"], lat: 47.5551, lng: 25.8889, qualityScore: 45 },
  { sourceRef: "sample/cafe-humor", name: "Cafeneaua Humor", nameEn: "Humor Coffee House", category: "cafe", subcategory: "coffee_shop", description: { ro: "Cafenea de specialitate cu prăjituri de casă.", en: "Specialty coffee house with homemade cakes." }, tags: ["cafea", "desert"], goodFor: ["relax", "rainy-day", "romantic"], lat: 47.5549, lng: 25.8905, openingHours: "08:00-20:00", qualityScore: 60, image: "/images/restaurant/cafe-house.webp" },
  { sourceRef: "sample/cofetaria-anca", name: "Cofetăria Anca", nameEn: "Anca Confectionery", category: "cafe", subcategory: "confectionery", description: { ro: "Cofetărie cu prăjituri tradiționale și înghețată.", en: "Confectionery with traditional cakes and ice cream." }, tags: ["desert"], goodFor: ["kids", "family"], lat: 47.5541, lng: 25.8879, qualityScore: 40 },
  { sourceRef: "sample/pub-central", name: "Central Pub", nameEn: "Central Pub", category: "bar", subcategory: "pub", description: { ro: "Pub cu bere artizanală și seri de muzică live.", en: "Pub with craft beer and live music nights." }, tags: ["bere", "muzică live"], goodFor: ["evening"], lat: 47.5552, lng: 25.8894, openingHours: "16:00-01:00", qualityScore: 55 },
  { sourceRef: "sample/piata-gura", name: "Piața Agroalimentară Gura Humorului", nameEn: "Gura Humorului Farmers Market", category: "market", subcategory: "marketplace", description: { ro: "Piață cu produse locale: brânzeturi, legume, miere.", en: "Market with local produce: cheeses, vegetables, honey." }, tags: ["produse locale"], goodFor: ["family", "culture"], lat: 47.5534, lng: 25.8926, openingHours: "07:00-15:00", qualityScore: 50 },
  { sourceRef: "sample/ferma-branza", name: "Ferma de Brânzeturi Bucovina", nameEn: "Bucovina Cheese Farm", category: "producer", subcategory: "cheese", description: { ro: "Producător artizanal de brânzeturi, cu degustări la fermă.", en: "Artisan cheese producer with on-farm tastings." }, tags: ["degustare"], goodFor: ["family", "culture"], lat: 47.5321, lng: 25.9204, qualityScore: 55, image: "/images/restaurant/cheese-producer.webp" },
  { sourceRef: "sample/mall-suceava", name: "Iulius Mall Suceava", nameEn: "Iulius Mall Suceava", category: "shopping", subcategory: "mall", description: { ro: "Mall cu magazine, cinema și food court, în Suceava.", en: "Mall with shops, cinema and food court, in Suceava." }, tags: ["indoor"], goodFor: ["rainy-day", "family"], lat: 47.6446, lng: 26.2431, website: "https://suceava.iuliusmall.com", qualityScore: 70 },
  { sourceRef: "sample/gara-gura", name: "Gara Gura Humorului Oraș", nameEn: "Gura Humorului Town Railway Station", category: "transport", subcategory: "station", description: { ro: "Stație CFR pe ruta Suceava–Vatra Dornei.", en: "Railway station on the Suceava–Vatra Dornei line." }, tags: ["tren"], goodFor: [], lat: 47.5504, lng: 25.8963, qualityScore: 45 },
  { sourceRef: "sample/aeroport-suceava", name: "Aeroportul Suceava (SCV)", nameEn: "Suceava Airport (SCV)", category: "transport", subcategory: "aerodrome", description: { ro: "Aeroport internațional, la circa 50 de minute cu mașina.", en: "International airport, about 50 minutes away by car." }, tags: ["aeroport"], goodFor: [], lat: 47.6875, lng: 26.3541, website: "https://www.aeroportsuceava.ro", qualityScore: 80 },
  { sourceRef: "sample/farmacia-catena", name: "Farmacie Centrală", nameEn: "Central Pharmacy", category: "health", subcategory: "pharmacy", description: { ro: "Farmacie în centrul orașului, program zilnic.", en: "Pharmacy in the town center, open daily." }, tags: [], goodFor: [], lat: 47.5547, lng: 25.8901, openingHours: "08:00-20:00", qualityScore: 40 },
  { sourceRef: "sample/spital-gura", name: "Spitalul Orășenesc Gura Humorului", nameEn: "Gura Humorului Town Hospital", category: "health", subcategory: "hospital", description: { ro: "Spital orășenesc cu urgențe.", en: "Town hospital with an ER." }, tags: [], goodFor: [], lat: 47.5568, lng: 25.8935, phone: "+40 230 232 442", qualityScore: 55 },
  { sourceRef: "sample/omv-gura", name: "Benzinărie OMV", nameEn: "OMV Fuel Station", category: "fuel", subcategory: "fuel", description: { ro: "Benzinărie non-stop la ieșirea spre Suceava.", en: "24/7 fuel station towards Suceava." }, tags: [], goodFor: [], lat: 47.5522, lng: 25.9012, openingHours: "24/7", qualityScore: 45 },
  { sourceRef: "sample/atm-bt", name: "Bancomat Banca Transilvania", nameEn: "Banca Transilvania ATM", category: "services", subcategory: "atm", description: { ro: "Bancomat în centrul orașului.", en: "ATM in the town center." }, tags: [], goodFor: [], lat: 47.5545, lng: 25.8896, qualityScore: 30 },
];

export function sampleScanResults(originLat: number, originLng: number, radiusKm: number): PlaceCandidate[] {
  return RAW.map((item) => {
    const distanceKm = Math.round(haversineKm(originLat, originLng, item.lat, item.lng) * 10) / 10;
    return { ...item, source: "sample" as const, distanceKm, driveMinutes: estimateDriveMinutes(distanceKm) };
  }).filter((p) => p.distanceKm <= radiusKm);
}
